name: Highcharts Visual Comparison
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'samples/**'
      - 'ts/**'
      - 'css/**'
      - '.github/workflows/visual-compare.yml'

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  file_size_comparison:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Check TypeScript version
        run: npx tsc -v

      - name: Build Highcharts
        run: npx gulp scripts

      - name: Build Dashboards
        run: npx gulp dashboards/scripts

      - name: Write file sizes at master
        run: npx gulp write-file-sizes --filename master.json

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0

      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Check TypeScript version
        run: npx tsc -v

      - name: Build Highcharts
        run: npx gulp scripts

      - name: Build Dashboards
        run: npx gulp dashboards/scripts

      - name: File size comparison
        run: |
          npx gulp write-file-sizes --filename ${{github.event.pull_request.number}}.json
          npx gulp write-size-table \
          --master ./tmp/filesizes/master.json \
          --proposed ./tmp/filesizes/${{github.event.pull_request.number}}.json

      - name: Comment PR with file size table
        if: ${{ github.event.pull_request.number && hashFiles('tmp/filesizes/comparison.md') != '' }}
        env:
          GH_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
          FILESIZES_COMMENT_USER: highsoft-bot
        run: |
          pr_number=${{ github.event.pull_request.number }}
          body_file="tmp/filesizes/comparison.md"
          comment_user="${FILESIZES_COMMENT_USER:-}"
          comment_filter="### File size comparison"

          if [ ! -f "${body_file}" ]; then
            echo "No comparison markdown found, skipping comment."
            exit 0
          fi

          repo="${{ github.repository }}"
          comments_json=$(gh api "repos/${repo}/issues/${pr_number}/comments")

          if [ -n "${comment_user}" ]; then
            comment_id=$(echo "${comments_json}" | jq -r --arg user "${comment_user}" --arg filter "${comment_filter}" \
              'map(select(.user.login == $user and ((.body // "") | contains($filter)))) | .[0].id // empty')
          else
            comment_id=$(echo "${comments_json}" | jq -r --arg filter "${comment_filter}" \
              'map(select((.body // "") | contains($filter))) | .[0].id // empty')
          fi

          if [ -n "${comment_id}" ]; then
            echo "Updating existing comment ${comment_id}"
            gh api "repos/${repo}/issues/comments/${comment_id}" \
              --method PATCH \
              -H "Accept: application/vnd.github+json" \
              -f body@"${body_file}" \
              >/dev/null
          else
            echo "Creating new file size comparison comment"
            gh pr comment "${pr_number}" --body-file "${body_file}" >/dev/null
          fi

      - name: Upload file size comparison artifact
        if: ${{ always() && hashFiles('tmp/filesizes/comparison.md') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: filesize-comparison-${{ github.event.pull_request.number || github.run_id }}
          path: |
            tmp/filesizes/master.json
            tmp/filesizes/${{ github.event.pull_request.number }}.json
            tmp/filesizes/comparison.md


  visual_compare:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build Highcharts
        run: npx gulp scripts

      - run: npx karma start test/karma-conf.js --tests highcharts/*/* --reference --browsercount 2 --no-fail-on-empty-test-suite
      - run: npx karma start test/karma-conf.js --tests maps/*/* --reference --browsercount 2 --no-fail-on-empty-test-suite
      - run: npx karma start test/karma-conf.js --tests stock/*/* --reference --browsercount 2 --no-fail-on-empty-test-suite
      - run: npx karma start test/karma-conf.js --tests gantt/*/* --reference --browsercount 2 --no-fail-on-empty-test-suite

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build Highcharts
        run: npx gulp scripts

      - run: npx karma start test/karma-conf.js --tests highcharts/*/* --single-run --browsercount 2 --visualcompare || true
      - run: npx karma start test/karma-conf.js --tests stock/*/* --single-run --browsercount 2 --visualcompare || true
      - run: npx karma start test/karma-conf.js --tests maps/*/* --single-run --browsercount 2 --visualcompare || true
      - run: npx karma start test/karma-conf.js --tests gantt/*/* --single-run --browsercount 2 --visualcompare || true

      - name: Comment on PR and upload visual test result
        run: |
          npx gulp update-pr-testresults \
          --fail-silently \
          --pr ${{github.event.pull_request.number}}
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{secrets.PR_COMMENT_TOKEN}}
          HIGHCHARTS_VISUAL_TESTS_BUCKET: ${{secrets.VISUAL_TESTS_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{secrets.VISUAL_TESTS_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.VISUAL_TESTS_AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.VISUAL_TESTS_AWS_REGION}}

      - name: Purge references with no candidate
        if: ${{ always() }}
        run: |
          find ./samples -type f -name "reference.svg" \
            -exec sh -c '
              for f do
                dir="$(dirname "$f")"
                candidate_path="$dir/candidate.svg"
                if [ ! -f "$candidate_path" ]; then
                  echo "Deleting unpaired reference: $f"
                  rm "$f"
                fi
              done
            ' sh {} +

      - name: Upload visual test images
        if: ${{ always() }}
        run: |
          aws s3 sync ./samples \
          "s3://$HIGHCHARTS_VISUAL_TESTS_BUCKET/visualtests/diffs/pullrequests/$PR_NUMBER/" \
          --exclude "*" \
          --include "*/reference.svg" \
          --include "*/candidate.svg" \
          --include "*/diff.gif"
        env:
          HIGHCHARTS_VISUAL_TESTS_BUCKET: ${{secrets.VISUAL_TESTS_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{secrets.VISUAL_TESTS_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.VISUAL_TESTS_AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.VISUAL_TESTS_AWS_REGION}}
          PR_NUMBER: ${{github.event.pull_request.number}}

      - name: Comment on PR
        uses: actions/github-script@v7
        if: ${{ always() }}
        with:
          github-token: ${{secrets.PR_COMMENT_TOKEN}}
          script: |
            const { createOrUpdateComment } = require('./.github/scripts/commentOnPR');
            const { readFileSync } = require('node:fs')
            const { title, body } = require('./tmp/pr-visual-test-comment.json');

            await createOrUpdateComment(github, context, title, body);


      - name: Store artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: visual-test-results
          path: |
            test/visual-test-results.json
            test/review-pr-*.json
            tmp/pr-visual-test-comment.json
